services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - clickhouse
    environment:
      - MONGO_URI=mongodb://mongo:27069/station_db
      - YANDEX_RASP_API_KEY_FILE=/run/secrets/yandex_rasp_api_key
    secrets:
      - yandex_rasp_api_key

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"

  mongo:
    image: mongo:latest
    ports:
      - "27069:27069"
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null --port 27069

volumes:
  mongo-data:

secrets:
  yandex_rasp_api_key:
    file: ./secrets/yandex_rasp_api_key.txt