[package]
name = "parsers"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
log = "0.4.21"
mongodb = "2.8"

[lib]
name = "parsers"
path = "src/lib.rs"